### ISSUE TITLE
Problem in downloading albedo data

### ISSUE THREAD

**Issue by usmansall** [lbusett/MODIStsp#122] opened 2018-04-06 10:17 UTC
Dear MODIStsp developers,
I want to download MODIS albedo data version 5 and 6 but unable to download using your package. I know MODIS is going to decommission version 5 data but I was also unable to download version 6 data using your package. Is there any update regarding this issue? Please let me know as I am a bit worried if there is a severe issue?

The operating system is windows 10 and R studio Version 1.0.143 – © 2009-2016 RStudio, Inc. and R version 3.4.3 (2017-11-30).
The albedo product is BRDF_Alb_WSA_B1_Daily_30ArcSec(MCD43D52) version 6 and nothing appear in the output spatial extent windows! to further proceed. thanks

Cheers!
Usman

**Comment by lbusett** [comment] 2018-04-06 10:25
Hi. 

Sorry, what do you mean by "nothing appear in the output spatial extent windows!"

Also, did you install the package from CRAN or from GitHub? 

Lorenzo

**Comment by usmansall** [comment] 2018-04-06 11:03
Hi,

I am using MODIStsp since last month and I downloaded it from Cran.

Everything was perfect so far. But today I had to download albedo data  
for the first time and when I select a particular albedo product then  
it does not activate options in output spatial extent windows of GUI,  
for example, "Required MODIS tiles" which means you cannot select any  
tile and thus go further. For some level 5 products, it takes spatial  
extent but it does not download data and give an error message.

It is downloading reflectance and LST data quite fine!

Best,

Usman

Quoting Lorenzo Busetto <notifications@github.com>:

**Comment by lbusett** [comment] 2018-04-06 11:53
Ok, thanks for the clarification. I see where the problem is and will have a fix out soon.

**Comment by lbusett** [comment] 2018-04-06 16:14
Hi, 
  
 I have a partial fix for this. Can you try installing this branch ? 

   library(devtools)
   install_github("lbusett/MODIStsp", ref = "hotfix/mcdproducts_extent")

and see if you manage to work with the albedo data ? Keep in mind that the product you are trying to access does not have tiles (i.e., only one file covering the whole globe is provided). Therefore, please do not try to use the tiles selector. You can select output extent using the bounding box or the (new) map selector. 

Let me know if it works

Lorenzo

**Comment by usmansall** [comment] 2018-04-06 18:03
Hi,

thank you so much, its working fine now. Have a great weekend.

Usman


Quoting Lorenzo Busetto <notifications@github.com>:

**Closed** 2018-04-07 15:11 UTC
